module.exports = {
  name: "Me",
  place: "Barrie",
  birth: 1986,
  death: null,
  siblings: 1,
  mom: {
    name: "Mom",
    place: "Montreal",
    birth: 1950,
    death: new Date().getFullYear(), //for the graph!!
    siblings: 0,
    mom: {
      name: "Nana",
      place: "Orillia",
      birth: 1923,
      death: 2017,
      siblings: 0,
      mom: {
        name: "Mabel Eaton",
        place: "Orillia",
        birth: 1897,
        death: 1988,
        siblings: 6,
        mom: {
          name: "Isabella Rawlston",
          place: "Orillia",
          birth: 1854,
          death: 1935,
          mom: {
            name: "Mary Jane Wesvig",
            place: "Orillia",
            birth: 1827,
          },
          dad: {
            name: "Alexander Rawlston",
            place: "Orillia",
            birth: 1824,
          },
        },
        dad: {
          name: "Edward Eaton",
          place: "Orillia",
          birth: 1856,
          death: 1944,
          mom: {
            name: "Lavina Ball",
            place: "Orillia",
            birth: 1828,
            death: 1915,
          },
          dad: {
            name: "James Eaton",
            place: "Ireland",
            birth: 1831,
            death: 1915,
          },
        },
      },
      dad: {
        name: "John Cameron",
        place: "Orillia",
        birth: 1893,
        death: 1976,
        siblings: 4,
        mom: {
          name: "Agnes Cotton",
          place: "Oro",
          death: 1930,
          birth: 1861,
          mom: {
            name: "Ann Cameron",
            place: "Scotland",
            birth: 1829,
          },
          dad: {
            name: "Jeremiah Cotton",
            place: "England",
            birth: 1823,
          },
        },
        dad: {
          name: "Donald Cameron",
          place: "Scotland",
          birth: 1855,
          death: 1922,
          mom: {
            name: "Margaret Littler",
            place: "England",
            birth: 1828,
            death: 1876,
          },
          dad: {
            name: "Malcom Cameron",
            place: "Scotland",
            birth: 1825,
            death: 1886,
          },
        },
      }
    },
    dad: {
      name: "Skipper",
      place: "Orillia",
      birth: 1921,
      death: 2003,
      siblings: 2,
      mom: {
        name: "Orphea Snider",
        place: "Belleville",
        birth: 1886,
        death: 1944,
        estimate: true,
        siblings: 6,
        mom: {
          name: "Elizabeth Gibbs",
          place: "Belleville",
          birth: 1862,
          death: 1940,
          mom: {
            name: "Sicela Gibbs",
            place: null,
            birth: 1842,
            estimate: true,
          },
          dad: {
            name: "Andrew Gibbs",
            place: null,
            birth: 1839,
            estimate: true,
          },
        },
        dad: {
          name: "Adam Snider",
          place: "St. Catherines",
          birth: 1852,
          death: 1921,
          mom: {
            name: "Almeda Milligan",
            place: "Brantford",
            birth: 1841,
          },
          dad: {
            name: "Zachariah Snider",
            place: "Belleville",
            birth: 1825,
          },
        },
      },
      dad: {
        name: "James Lawrence",
        place: "Bracebridge",
        birth: 1882,
        death: 1944,
        siblings: 6,
        mom: {
          name: "Christina McLean",
          place: "Scotland/Perry Sound",
          birth: 1841,
          death: 1923,
          mom: {
            name: "Mary Muir",
            place: "Scotland",
            birth: 1864,
          },
          dad: {
            name: "Colin McLean",
            place: "Scotland",
            birth: 1849,
          },
        },
        dad: {
          name: "James Lawrence",
          place: "Ireland/Perry Sound",
          birth: 1833,
          death: 1921,
          mom: {
            name: "Ann Lawrence",
            place: "Ireland",
            birth: 1818,
          },
          dad: {
            name: "James Lawrence",
            place: "England",
            birth: 1818,
          },
        },
      },
    },
  },
  dad: {
    name: "Dad",
    place: "Kingston",
    birth: 1952,
    death: new Date().getFullYear(), //for the graph!!
    siblings: 4,
    mom: {
      name: "Grandma",
      place: "Athens",
      birth: 1916,
      death: 2002,
      siblings: 1,
      mom: {
        name: "Ethel Berney",
        place: "Athens",
        birth: 1889,
        death: 1919,
        siblings: 7,
        mom: {
          name: "Rosa Ann Moran",
          place: "Athens",
          birth: 1855,
          death: 1919,
          mom: {
            name: "Hanora Moran",
            place: null,
            birth: 1828,
            estimate: true,
          },
          dad: {
            name: "James Moran",
            place: "Ireland",
            birth: 1825,
          },
        },
        dad: {
          name: "Abel Barny",
          place: "Athens",
          birth: 1852,
          death: 1937,
          mom: {
            name: "Abigail Wright",
            place: "Athens",
            birth: 1814,
          },
          dad: {
            name: "William Berney",
            place: "Athens",
            birth: 1804,
          },
        },
      },
      dad: {
        name: "Oran Robinson",
        place: "Brockville",
        birth: 1889,
        death: 1919,
        siblings: 4,
        mom: {
          name: "Keziah Yates",
          place: "Lyndhurst",
          birth: 1862,
          death: 1954,
          mom: {
            name: "Cynthia Ann Booth",
            place: "Athens",
            birth: 1840,
          },
          dad: {
            name: "Gerhom Yates",
            place: "Athens",
            birth: 1829,
          },
        },
        dad: {
          name: "George Robinson",
          place: "Athens",
          birth: 1859,
          death: 1939,
          mom: {
            name: "Clarinda Wing",
            place: "Athens",
            birth: 1832,
          },
          dad: {
            name: "Abraham Robeson",
            place: "Athens",
            birth: 1828,
          },
        },
      },
    },
    dad: {
      name: "Papa",
      place: "Delta",
      birth: 1913,
      death: 1981,
      siblings: 2,
      mom: {
        name: "Clara Arnold",
        place: "Brockville",
        birth: 1880,
        death: 1949,
        siblings: 0,
        mom: {
          name: "Lucy Blancher",
          place: "Brockville",
          birth: 1852,
          death: 1932,
          mom: {
            name: "Hulda Blanchard",
            place: null,
            birth: 1811,
            estimate: true,
          },
          dad: {
            name: "Charles Blanchard",
            place: null,
            birth: 1811,
          },
        },
        dad: {
          name: "Omer Arnold",
          place: "Athens",
          death: 1943,
          birth: 1856,
          mom: {
            name: "Caroline Webster",
            place: null,
            birth: 1827,
            death: 1907,
          },
          dad: {
            name: "Richard Arnold",
            place: null,
            birth: 1821,
            death: 1906,
          },
        },
      },
      dad: {
        name: "Joseph Kelly",
        place: "Athens",
        birth: 1879,
        death: 1946,
        siblings: 3,
        mom: {
          name: "Mary Ann Topping",
          place: "Athens",
          birth: 1850,
          death: 1927,
          mom: {
            name: "Ellen Cavanaugh",
            place: "Ireland",
            birth: 1831,
          },
          dad: {
            name: "George Topping",
            place: "Ireland",
            birth: 1824,
          }
        },
        dad: {
          name: "Richard Kelly",
          place: "Athens",
          birth: 1852,
          death: 1928,
          mom: {
            name: "Eliza Ennis",
            place: "Athens",
            birth: 1826,
          },
          dad: {
            name: "Richard Kelly",
            place: "Athens",
            birth: 1818,
          },
        },
      },
    },
  },
};
