// {
//   name: "",
//   place: null,
//   birth: null,
//   siblings:null,
//   mom: {},
//   dad: {},
// }


module.exports = {
  name: "Me",
  place: "Barrie",
  birthday: 1986,
  siblings: 1,
  mom: {
    name: "Mom",
    place: "Montreal",
    birth: 1950,
    siblings: 0,
    mom: {
      name: "Grandma",
      place: "Orillia",
      birth: null,
      siblings: 0,
      mom: {
        name: "Mabel Eaton",
        place: "Orillia",
        birth: 1897,
        siblings: 6,
        mom: {
          name: "Isabella Rawlston",
          place: "Orillia",
          birth: 1854,
          siblings: null,
          mom: {
            name: "Mary Jane Wesvig",
            place: "Orillia",
            birth: 1827,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Alexander Rawlston",
            place: "Orillia",
            birth: 1824,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "Edward Eaton",
          place: "Orillia",
          birth: 1856,
          siblings: null,
          mom: {
            name: "Lavina Ball",
            place: "Orillia",
            birth: 1828,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "James Eaton",
            place: "Ireland",
            birth: 1831,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
      dad: {
        name: "John Cameron",
        place: "Orillia",
        birth: 1893,
        siblings: 4,
        mom: {
          name: "Agnes Cotton",
          place: "Oro",
          birth: 1861,
          siblings: null,
          mom: {
            name: "Ann Cameron",
            place: "Scotland",
            birth: 1829,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Jeremiah Cotton",
            place: "England",
            birth: 1823,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "Donald Cameron",
          place: "Scotland",
          birth: 1855,
          siblings: null,
          mom: {
            name: "Margaret Littler",
            place: "England",
            birth: 1828,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Malcom Cameron",
            place: "Scotland",
            birth: 1825,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      }
    },
    dad: {
      name: "Grandpa",
      place: "Orillia",
      birth: 1952,
      siblings: 2,
      mom: {
        name: "Orphea Snider",
        place: "Belleville",
        birth: 1886,
        siblings: 6,
        mom: {
          name: "Elizabeth Gibbs",
          place: "Belleville",
          birth: 1862,
          siblings: null,
          mom: {
            name: "Sicela Gibbs",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Andrew Gibbs",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "Adam Snider",
          place: "St. Catherines",
          birth: 1852,
          siblings: null,
          mom: {
            name: "Almeda Milligan",
            place: "Brantford",
            birth: 1841,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Zachariah Snider",
            place: "Belleville",
            birth: 1825,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
      dad: {
        name: "James Lawrence",
        place: "Bracebridge",
        birth: 1882,
        siblings: 6,
        mom: {
          name: "Christina McLean",
          place: "Scotland/Perry Sound",
          birth: 1841,
          siblings: null,
          mom: {
            name: "Mary Muir",
            place: "Scotland",
            birth: 1864,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Colin McLean",
            place: "Scotland",
            birth: 1849,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "James Lawrence",
          place: "Ireland/Perry Sound",
          birth: 1833,
          siblings: null,
          mom: {
            name: "Ann Lawrence",
            place: "Ireland",
            birth: 1818,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "James Lawrence",
            place: "England",
            birth: 1818,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
    },
  },
  dad: {
    name: "Dad",
    place: "Kingston",
    birth: 1952,
    siblings: 4,
    mom: {
      name: "Grandma",
      place: "Athens",
      birth: 1916,
      siblings: 1,
      mom: {
        name: "Ethel Berney",
        place: "Athens",
        birth: 1889,
        siblings: 7,
        mom: {
          name: "Rosa Ann Moran",
          place: "Athens",
          birth: 1855,
          siblings: null,
          mom: {
            name: "Hanora Moran",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "James Moran",
            place: "Ireland",
            birth: 1825,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "Abel Barny",
          place: "Athens",
          birth: 1852,
          siblings: null,
          mom: {
            name: "Abigail Wright",
            place: "Athens",
            birth: 1814,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "William Berney",
            place: "Athens",
            birth: 1804,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
      dad: {
        name: "Oran Robinson",
        place: "Brockville",
        birth: 1889,
        siblings: 4,
        mom: {
          name: "Keziah Yates",
          place: "Lyndhurst",
          birth: 1862,
          siblings: null,
          mom: {
            name: "Cynthia Ann Booth",
            place: "Athens",
            birth: 1840,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Gerhom Yates",
            place: "Athens",
            birth: 1829,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "George Robinson",
          place: "Athens",
          birth: 1859,
          siblings: null,
          mom: {
            name: "Clarinda Wing",
            place: "Athens",
            birth: 1832,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Abraham Robeson",
            place: "Athens",
            birth: 1828,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
    },
    dad: {
      name: "Grandpa",
      place: "Delta",
      birth: 1913,
      siblings: 2,
      mom: {
        name: "Clara Arnold",
        place: "Brockville",
        birth: 1880,
        siblings: 0,
        mom: {
          name: "Lucy Blancher",
          place: "Brockville",
          birth: 1852,
          siblings: null,
          mom: {
            name: "Hulda Blanchard",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Charles Blanchard",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
        dad: {
          name: "Omer Arnold",
          place: "Athens",
          birth: 1856,
          siblings: null,
          mom: {
            name: "Caroline Webster",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Richard Arnold",
            place: null,
            birth: null,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
      dad: {
        name: "Joseph Kelly",
        place: "Athens",
        birth: 1879,
        siblings: 3,
        mom: {
          name: "Mary Ann Topping",
          place: "Athens",
          birth: 1850,
          siblings: null,
          mom: {
            name: "Ellen Cavanaugh",
            place: "Ireland",
            birth: 1831,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "George Topping",
            place: "Ireland",
            birth: 1824,
            siblings: null,
            mom: {},
            dad: {},
          }
        },
        dad: {
          name: "Richard Kelly",
          place: "Athens",
          birth: 1852,
          siblings: null,
          mom: {
            name: "Eliza Ennis",
            place: "Athens",
            birth: 1826,
            siblings: null,
            mom: {},
            dad: {},
          },
          dad: {
            name: "Richard Kelly",
            place: "Athens",
            birth: 1818,
            siblings: null,
            mom: {},
            dad: {},
          },
        },
      },
    },
  },
}
