// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var ContainerSurface, Easing, Engine, Modifier, RenderNode, Surface, Transform, Transitionable, mainContext, wave;
  Engine = require("famous/core/Engine");
  Transform = require("famous/core/Transform");
  Modifier = require("famous/core/Modifier");
  Surface = require("famous/core/Surface");
  Transitionable = require("famous/transitions/Transitionable");
  ContainerSurface = require("famous/surfaces/ContainerSurface");
  Easing = require("famous/transitions/Easing");
  RenderNode = require("famous/core/RenderNode");
  mainContext = Engine.createContext();
  wave = function() {
    var color, duration, make_radian, move, node, r, rockout, rotate, surf, x, y;
    r = parseInt(Math.random() * 28) - 14;
    color = "rgb(" + (54 + r) + "," + (111 + r) + "," + (159 + r) + ")";
    surf = new Surface({
      size: [500, 100],
      properties: {
        backgroundColor: color,
        "border-radius": "2px"
      }
    });
    duration = function() {
      return (Math.random() * 2200) + 1500;
    };
    make_radian = function() {
      return 0.04 * Math.random();
    };
    x = (Math.random() * 1000) - 500;
    y = Math.random() * 55;
    move = new Modifier({
      transform: Transform.translate(x, y, 0)
    });
    rotate = new Modifier({
      origin: [0.5, 1.1],
      opacity: 0.75,
      transform: Transform.rotateZ(make_radian() * ((Math.random() * 2) - .1))
    });
    node = new RenderNode();
    node.add(move).add(rotate).add(surf);
    rockout = function(d) {
      var ease;
      ease = {
        duration: duration,
        curve: Easing.inOutQuad
      };
      ease.duration = duration();
      r = make_radian() * (2 * d);
      return rotate.setTransform(Transform.rotateZ(r), ease, function() {
        return rockout(d * -1);
      });
    };
    setTimeout((function() {
      var d;
      d = Math.round(Math.random());
      return rockout(d);
    }), Math.random() * 1500);
    return node;
  };
  return module.exports = wave;
});

/*
//@ sourceMappingURL=wave.map
*/
